### ISSUE TITLE
Has your code worked?

### ISSUE THREAD

**Issue by clemsciences** [mpsilfve/phonembedding#4]
I run main.py and I get this error

```txt
1. CORRELATION EXPERIMENTS
--------------------------

Traceback (most recent call last):
  File "C:/Users/clement_besnier/PycharmProjects/phonembedding_origin/src/main.py", line 107, in <module>
    correlation_experiment("../data/finnish","FI",getsvdembs,"SVD")
  File "C:/Users/clement_besnier/PycharmProjects/phonembedding_origin/src/main.py", line 74, in correlation_experiment
    featsim = getsimmatrix(lanfeatures,len(cencoder), embchars)
  File "C:\Users\clement_besnier\PycharmProjects\phonembedding_origin\src\correlation.py", line 14, in getsimmatrix
    corrmat[i][j] = cossim(e.reshape(1,-1),d.reshape(1,-1))
AttributeError: 'NoneType' object has no attribute 'reshape'
```

which means that *lanfeatures* contains None elements.

Moreover, why do you have two data folders with the same data?

I'm sorry if my comments annoy you. In such case, I would not bother you anymore. Otherwise, I can propose you a pull request with clean code.

**Comment by mpsilfve** [comment]
Hi,

Yeah. It works when I run it on my own laptop. Something must have changed in DyNet. I'll check my version when I get home tonight.

I don't think there are two data directories.

It's fine :) I also want the code to run.

**Comment by mpsilfve** [comment]
Hi Clement,

This is what I did to make it run:

pip3 install dynet
pip3 install scipy
pip3 install gensim
python3 main.py

Hope it helps!

**Comment by clemsciences** [comment]
Hey!

So, on Windows 10, it does not work but on a Debian Stretch, it works! Thanks!

What I can do is just to suggect to put a requirements.txt file at the top of your repository

```
numpy==1.15.4
scipy==1.1.0
scikit-learn==0.20.1
gensim==3.6.0
dynet==2.0.3
```

and to remove one of the two *data* folders.
